---
title: "Re-analysis of Feit et al. (2016)"
output: html_notebook
---

```{r setup, include = FALSE}
library(tidyverse)
source("R/commons.R") # load functions that are shared across notebooks
library("readxl")
library("openxlsx")
```

Use Markdown to explain your analysis. Your code goes into each chunk like below.

```{r}
#data_file_paths <- list.files("data", full.names = TRUE)
mixed =list.files("data",pattern="[^(a-zA-Z)]*(Mix)[^(a-zA-Z)]*", full.names = TRUE)
random =list.files("data",pattern="[^(a-zA-Z)]*(Random)[^(a-zA-Z)]*", full.names = TRUE)
sentence =list.files("data",pattern="[^(a-zA-Z)]*(Sentence)[^(a-zA-Z)]*", full.names = TRUE)

# 2 x 1 touch typist
read_xls <- read.xlsx("Background.xlsx")


touch_typist <- which(read_xls$`Do.you.use.the.touch.typing.system.with.all.10.fingers?.If.so,.how.many.years.of.experience.do.you.have?`>= 1)
non_touch_typist <- which(read_xls$`Do.you.use.the.touch.typing.system.with.all.10.fingers?.If.so,.how.many.years.of.experience.do.you.have?`< 1)

touch_typist_id <- read_xls[c(touch_typist),1]
non_touch_typist_id <- read_xls[c(non_touch_typist),1]



#non_touch_typist <- which(read_xls[13] <= 1)
#n <- subset(read_xls, select = c(touch_typist) )

```

Extract data:
```{r}
i = 0
vars <- c("mixed", "random", "sentence")
for (var in vars){
  i = 0
  for (path in eval(parse(text=var))){
    if (i == 0){
    nam <- paste(var, "mod", sep="_")
    tabcurr <- read.table(file=path, sep="\t", quote="", comment.char="")
    colnames(tabcurr) <- lapply(tabcurr[1, ], as.character)
    tabcurr <- tabcurr[-1,]
    assign(nam, tabcurr)

    }
    else{
    newtab <- read.table(file=path, sep="\t", quote="", comment.char="")
    colnames(newtab) <- lapply(newtab[1, ], as.character)
    newtab <- newtab[-1,]
    chars <- as.character("mixed_mod")

   if (nam[[1]] == as.character("mixed_mod")){
     mixed_mod <- rbind(newtab, mixed_mod)
   } else if (nam[[1]] == as.character("random_mod")){
     random_mod <- rbind(newtab, random_mod)
   } else if (nam[[1]] == as.character("sentence_mod")){
     sentence_mod <- rbind(newtab, sentence_mod)
   }
    
  }
  i <- i + 1
  }
  }

```
##Linear Model for WMP:
```{r}
# typeist/nontypist = response var ahand vo wmp ist wkeit in gruppe von ty or nty so höcht.
sentence_mod <- as.data.frame.matrix(sentence_mod)
mixed_mod <- as.data.frame.matrix(mixed_mod)
random_mod <- as.data.frame.matrix(random_mod)
condition_list <- list(sentence_mod, mixed_mod, random_mod)
names_of_dataframes <- list("sentence_mod", "mixed_mod", "random_mod")
i = 1
for (df in condition_list){
  new_nam <- paste(names_of_dataframes[i] , "wmp", sep="_")
  
  assign(new_nam, df %>% group_by(user_id, current_input) %>% summarise(m = mean(as.numeric(wpm)))%>% group_by(user_id) %>% summarise(mean_person = mean(as.numeric(m))))
  
currnam <-  df %>% group_by(user_id, current_input) %>% summarise(m = mean(as.numeric(wpm)))%>% group_by(user_id) %>% summarise(mean_person = mean(as.numeric(m)))

tt <- paste("TouchTypist" , names_of_dataframes[i], sep="_")
ntt <- paste("NonTouchTypist" , names_of_dataframes[i], sep="_")

assign(tt, currnam[currnam$user_id %in% c(touch_typist_id),])
 assign(ntt, currnam[currnam$user_id %in% c(non_touch_typist_id),]) 
#filtertt <- t2[t2$user_id %in% c(touch_typist_id),]
  i <- i + 1
  
}
```